version: '2.2'
services: 
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato
    ports:
      - 3307:3306 
  spring-boot:
    image: hamza1991/tpachatprojctbackend
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    restart: on-failure  

  